import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import pg from 'pg';
import { Migrator } from '../storage/migrator.js';
import { EventsStorage } from '../events/storage.js';
import path from 'path';

const TEST_DB = process.env.TEST_DATABASE_URL || 'postgres://memory:memory@localhost:5432/team_memory_test';
const PID = '00000000-0000-0000-0000-00000000eeee';

describe('EventsStorage', () => {
  let pool: pg.Pool;
  let storage: EventsStorage;

  beforeAll(async () => {
    pool = new pg.Pool({ connectionString: TEST_DB });
    await new Migrator(pool, path.resolve('src/storage/migrations')).run();
    await pool.query(`DELETE FROM project_events WHERE project_id = $1`, [PID]);
    await pool.query(`DELETE FROM projects WHERE id = $1`, [PID]);
    await pool.query(`INSERT INTO projects (id, name) VALUES ($1, 'events-storage-test')`, [PID]);
    storage = new EventsStorage(pool);
  });

  beforeEach(async () => {
    await pool.query(`DELETE FROM project_events WHERE project_id = $1`, [PID]);
  });

  afterAll(async () => {
    await pool.query(`DELETE FROM project_events WHERE project_id = $1`, [PID]);
    await pool.query(`DELETE FROM projects WHERE id = $1`, [PID]);
    await pool.end();
  });

  it('insert and list returns the inserted event', async () => {
    const ev = await storage.insert({
      projectId: PID,
      eventType: 'merge',
      occurredAt: new Date(),
      title: 'feat/foo merged to main',
      refs: { pr_number: 42 },
    });
    expect(ev.id).toBeDefined();
    expect(ev.refs.pr_number).toBe(42);
    expect(ev.autoGenerated).toBe(false);

    const list = await storage.list(PID, { limit: 10 });
    expect(list).toHaveLength(1);
    expect(list[0].title).toContain('foo');
  });

  it('list orders by occurred_at DESC', async () => {
    await storage.insert({ projectId: PID, eventType: 'merge', occurredAt: new Date('2026-05-01'), title: 'old' });
    await storage.insert({ projectId: PID, eventType: 'merge', occurredAt: new Date('2026-05-12'), title: 'new' });
    const list = await storage.list(PID, { limit: 10 });
    expect(list[0].title).toBe('new');
    expect(list[1].title).toBe('old');
  });

  it('filters by event_type', async () => {
    await storage.insert({ projectId: PID, eventType: 'merge', occurredAt: new Date(), title: 'm' });
    await storage.insert({ projectId: PID, eventType: 'deploy', occurredAt: new Date(), title: 'd' });
    const merges = await storage.list(PID, { eventType: 'merge' });
    expect(merges).toHaveLength(1);
    expect(merges[0].title).toBe('m');
  });

  it('filters by since (occurred_at >=)', async () => {
    await storage.insert({ projectId: PID, eventType: 'merge', occurredAt: new Date('2026-05-01'), title: 'old' });
    await storage.insert({ projectId: PID, eventType: 'merge', occurredAt: new Date('2026-05-12'), title: 'new' });
    const recent = await storage.list(PID, { since: new Date('2026-05-10') });
    expect(recent).toHaveLength(1);
    expect(recent[0].title).toBe('new');
  });

  it('delete removes event and returns true', async () => {
    const ev = await storage.insert({ projectId: PID, eventType: 'merge', occurredAt: new Date(), title: 'x' });
    const ok = await storage.delete(ev.id);
    expect(ok).toBe(true);
    const list = await storage.list(PID);
    expect(list).toHaveLength(0);
  });

  it('delete returns false on unknown id', async () => {
    const ok = await storage.delete('00000000-0000-0000-0000-000000000000');
    expect(ok).toBe(false);
  });
});
