import { describe, it, expect } from 'vitest';
import {
  buildEventsPrompt,
  parseEventsResponse,
  parseEventsResponseStrict,
  EventsParseError,
} from '../events/extractor.js';

describe('Events extractor', () => {
  it('builds prompt mentioning all 5 event types', () => {
    const prompt = buildEventsPrompt({
      summary: 'session summary',
      messages: [{ role: 'user', content: 'смержил v4.5 в main' }],
    });
    expect(prompt).toContain('merge');
    expect(prompt).toContain('release');
    expect(prompt).toContain('deploy');
    expect(prompt).toContain('incident');
    expect(prompt).toContain('milestone');
  });

  it('parses valid JSON with merge + release events', () => {
    const json = JSON.stringify({
      events: [
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'v4.5 to main', refs: { pr_number: 40 }, confidence: 0.95 },
        { event_type: 'release', occurred_at: '2026-05-12T15:00:00Z', title: 'v4.5.0', refs: { version_tag: 'v4.5.0' }, confidence: 0.9 },
      ],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed).toHaveLength(2);
    expect(parsed[0].eventType).toBe('merge');
    expect(parsed[0].refs?.pr_number).toBe(40);
    expect(parsed[1].refs?.version_tag).toBe('v4.5.0');
  });

  it('filters out low-confidence events (default threshold 0.55)', () => {
    // Phase 5.A: threshold lowered from 0.7 → 0.55 to capture routine
    // events (refactor/bugfix mentions) that LLM scores 0.55-0.68.
    // confidence=0.4 is below, 0.6 above, 0.9 well above — only the
    // first should be filtered.
    const json = JSON.stringify({
      events: [
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'maybe', confidence: 0.4 },
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'likely', confidence: 0.6 },
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'sure', confidence: 0.9 },
      ],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed).toHaveLength(2);
    expect(parsed.map(p => p.title)).toEqual(['likely', 'sure']);
  });

  it('respects custom minConfidence', () => {
    const json = JSON.stringify({
      events: [
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 't', confidence: 0.85 },
      ],
    });
    expect(parseEventsResponse(json, { minConfidence: 0.9 })).toHaveLength(0);
    expect(parseEventsResponse(json, { minConfidence: 0.8 })).toHaveLength(1);
  });

  it('returns empty array on invalid JSON', () => {
    expect(parseEventsResponse('not-json')).toEqual([]);
  });

  it('returns empty on missing events key', () => {
    expect(parseEventsResponse('{}')).toEqual([]);
  });

  it('rejects unknown event_type', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'unknown', occurred_at: '2026-05-12T14:00:00Z', title: 'x', confidence: 0.9 }],
    });
    expect(parseEventsResponse(json)).toEqual([]);
  });

  it('marks all extracted events as autoGenerated=true', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'release', occurred_at: '2026-05-12T14:00:00Z', title: 'v1', confidence: 0.9 }],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed[0].autoGenerated).toBe(true);
  });

  it('skips events with empty title', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: '', confidence: 0.9 }],
    });
    expect(parseEventsResponse(json)).toEqual([]);
  });

  it('trims whitespace from title', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: '  foo  ', confidence: 0.9 }],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed[0].title).toBe('foo');
  });

  describe('parseEventsResponseStrict (5.E retry support)', () => {
    it('throws EventsParseError on invalid JSON', () => {
      expect(() => parseEventsResponseStrict('not json')).toThrow(EventsParseError);
      expect(() => parseEventsResponseStrict('not json')).toThrow(/not valid JSON/);
    });

    it('throws EventsParseError when payload is not an object', () => {
      expect(() => parseEventsResponseStrict('"a string"')).toThrow(EventsParseError);
    });

    it('throws EventsParseError when `events` is missing or not an array', () => {
      expect(() => parseEventsResponseStrict('{}')).toThrow(/missing `events` array/);
      expect(() => parseEventsResponseStrict('{"events":42}')).toThrow(/missing `events` array/);
    });

    it('returns the same parsed events as the non-strict variant on success', () => {
      const json = JSON.stringify({
        events: [
          { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'feat/x merged', confidence: 0.9 },
        ],
      });
      expect(parseEventsResponseStrict(json)).toEqual(parseEventsResponse(json));
    });

    it('returns [] when events array is empty (legitimate empty response)', () => {
      // Empty array is a valid LLM response (no events in this session) and
      // must NOT throw — only malformed/missing structure throws.
      expect(parseEventsResponseStrict('{"events":[]}')).toEqual([]);
    });

    it('strips a ```json markdown fence before parsing (prod log signature)', () => {
      // qwen3.5:4b wraps its reply in a fence despite the prompt; the strict
      // parser must normalize before JSON.parse. Signature from prod log:
      // EventsParseError at dist/events/extractor.js — Unexpected token '`'.
      const fenced = '```json\n{"events":[]}\n```';
      expect(parseEventsResponseStrict(fenced)).toEqual([]);
    });

    it('strips a bare ``` fence and returns the contained event', () => {
      const event = {
        event_type: 'merge',
        occurred_at: '2026-05-12T14:00:00Z',
        title: 'feat/x merged into main',
        confidence: 0.9,
      };
      const fenced = '```\n' + JSON.stringify({ events: [event] }) + '\n```';
      const parsed = parseEventsResponseStrict(fenced);
      expect(parsed).toHaveLength(1);
      expect(parsed[0].eventType).toBe('merge');
    });

    it('strips a <think> reasoning block followed by a fenced payload', () => {
      const raw = '<think>no events here</think>\n```json\n{"events":[]}\n```';
      expect(parseEventsResponseStrict(raw)).toEqual([]);
    });

    it('still parses plain unwrapped JSON (no regression)', () => {
      const json = JSON.stringify({
        events: [
          { event_type: 'release', occurred_at: '2026-05-12T14:00:00Z', title: 'v5 shipped', confidence: 0.8 },
        ],
      });
      expect(parseEventsResponseStrict(json)).toHaveLength(1);
    });
  });
});
