import { describe, it, expect } from 'vitest';
import { buildEventsPrompt, parseEventsResponse } from '../events/extractor.js';

describe('Events extractor', () => {
  it('builds prompt mentioning all 5 event types', () => {
    const prompt = buildEventsPrompt({
      summary: 'session summary',
      messages: [{ role: 'user', content: 'смержил v4.5 в main' }],
    });
    expect(prompt).toContain('merge');
    expect(prompt).toContain('release');
    expect(prompt).toContain('deploy');
    expect(prompt).toContain('incident');
    expect(prompt).toContain('milestone');
  });

  it('parses valid JSON with merge + release events', () => {
    const json = JSON.stringify({
      events: [
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'v4.5 to main', refs: { pr_number: 40 }, confidence: 0.95 },
        { event_type: 'release', occurred_at: '2026-05-12T15:00:00Z', title: 'v4.5.0', refs: { version_tag: 'v4.5.0' }, confidence: 0.9 },
      ],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed).toHaveLength(2);
    expect(parsed[0].eventType).toBe('merge');
    expect(parsed[0].refs?.pr_number).toBe(40);
    expect(parsed[1].refs?.version_tag).toBe('v4.5.0');
  });

  it('filters out low-confidence events (default threshold 0.7)', () => {
    const json = JSON.stringify({
      events: [
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'might', confidence: 0.3 },
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 'sure', confidence: 0.9 },
      ],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed).toHaveLength(1);
    expect(parsed[0].title).toBe('sure');
  });

  it('respects custom minConfidence', () => {
    const json = JSON.stringify({
      events: [
        { event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: 't', confidence: 0.85 },
      ],
    });
    expect(parseEventsResponse(json, { minConfidence: 0.9 })).toHaveLength(0);
    expect(parseEventsResponse(json, { minConfidence: 0.8 })).toHaveLength(1);
  });

  it('returns empty array on invalid JSON', () => {
    expect(parseEventsResponse('not-json')).toEqual([]);
  });

  it('returns empty on missing events key', () => {
    expect(parseEventsResponse('{}')).toEqual([]);
  });

  it('rejects unknown event_type', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'unknown', occurred_at: '2026-05-12T14:00:00Z', title: 'x', confidence: 0.9 }],
    });
    expect(parseEventsResponse(json)).toEqual([]);
  });

  it('marks all extracted events as autoGenerated=true', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'release', occurred_at: '2026-05-12T14:00:00Z', title: 'v1', confidence: 0.9 }],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed[0].autoGenerated).toBe(true);
  });

  it('skips events with empty title', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: '', confidence: 0.9 }],
    });
    expect(parseEventsResponse(json)).toEqual([]);
  });

  it('trims whitespace from title', () => {
    const json = JSON.stringify({
      events: [{ event_type: 'merge', occurred_at: '2026-05-12T14:00:00Z', title: '  foo  ', confidence: 0.9 }],
    });
    const parsed = parseEventsResponse(json);
    expect(parsed[0].title).toBe('foo');
  });
});
