// src/__tests__/retrieval-sources.test.ts
//
// Unit tests for the three KnowledgeSource implementations. Embedding
// provider and vector store are mocked so we can verify filter shape,
// hydration logic, and authorization gates without a live cluster.

import { describe, it, expect, vi } from 'vitest';
import { EntriesSource } from '../retrieval/sources/entries-source.js';
import { SessionsSource } from '../retrieval/sources/sessions-source.js';
import { MessagesSource } from '../retrieval/sources/messages-source.js';

function mockEmbed(ready = true) {
  return {
    isReady: () => ready,
    dimensions: 768,
    embed: vi.fn(async () => Array(768).fill(0)),
    embedBatch: vi.fn(async () => []),
    close: vi.fn(),
  };
}

function mockStore(hits: Array<{ id: string; score: number; payload?: Record<string, unknown> }>) {
  return {
    search: vi.fn(async () => hits.map(h => ({ ...h, payload: h.payload ?? {} }))),
    upsert: vi.fn(),
    upsertBatch: vi.fn(),
    delete: vi.fn(),
    deleteByFilter: vi.fn(),
    setPayload: vi.fn(),
    ensureCollection: vi.fn(),
    createPayloadIndex: vi.fn(),
    getPointCount: vi.fn(),
    collectionExists: vi.fn(),
    close: vi.fn(),
  };
}

describe('EntriesSource', () => {
  const projectId = '00000000-0000-0000-0000-000000000000';
  const entry = (id: string) => ({
    id,
    projectId,
    category: 'decisions',
    domain: null,
    title: `Entry ${id}`,
    content: 'Body content',
    author: 'auto-extractor',
    tags: ['t'],
    priority: 'medium' as const,
    status: 'active' as const,
    pinned: false,
    relatedIds: [],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    importanceScore: 0.7,
    confirmationCount: 2,
    autoGenerated: true,
  });

  it('returns empty when embedding provider not ready', async () => {
    const src = new EntriesSource(
      mockEmbed(false) as never,
      mockStore([]) as never,
      { getByIds: vi.fn() } as never,
    );
    const out = await src.search('q', { project_id: projectId }, 10);
    expect(out).toEqual([]);
  });

  it('hydrates Qdrant hits via getByIds', async () => {
    const store = mockStore([{ id: 'A', score: 0.9 }, { id: 'B', score: 0.8 }]);
    const storage = {
      getByIds: vi.fn(async () => [entry('A'), entry('B')]),
    };
    const src = new EntriesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    const out = await src.search('q', { project_id: projectId }, 10);
    expect(out).toHaveLength(2);
    expect(out[0].source_type).toBe('entries');
    expect(out[0].source_id).toBe('A');
    expect(out[0].score).toBeCloseTo(0.9);
    expect(out[0].text).toContain('Entry A');
    expect(out[0].metadata.category).toBe('decisions');
    expect(storage.getByIds).toHaveBeenCalledWith(projectId, ['A', 'B']);
  });

  it('drops Qdrant hits whose PG row is missing', async () => {
    const store = mockStore([{ id: 'A', score: 0.9 }, { id: 'GONE', score: 0.8 }]);
    const storage = { getByIds: vi.fn(async () => [entry('A')]) };
    const src = new EntriesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    const out = await src.search('q', { project_id: projectId }, 10);
    expect(out).toHaveLength(1);
    expect(out[0].source_id).toBe('A');
  });

  it('forwards categories filter as Qdrant should-clauses', async () => {
    const store = mockStore([]);
    const storage = { getByIds: vi.fn(async () => []) };
    const src = new EntriesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    await src.search(
      'q',
      { project_id: projectId, categories: ['decisions', 'conventions'] },
      10,
    );
    const filter = (store.search.mock.calls[0][2] ?? {}) as {
      should?: Array<{ key: string; match: { value: string } }>;
    };
    expect(filter.should).toEqual([
      { key: 'category', match: { value: 'decisions' } },
      { key: 'category', match: { value: 'conventions' } },
    ]);
  });
});

describe('SessionsSource', () => {
  const projectId = '00000000-0000-0000-0000-000000000000';

  it('hydrates sessions via getSession', async () => {
    const store = mockStore([
      { id: 'S1', score: 0.85 },
      { id: 'S2', score: 0.7 },
    ]);
    const storage = {
      getSession: vi.fn(async (id: string) => ({
        id,
        agentTokenId: 'agent',
        projectId,
        externalId: null,
        name: `Session ${id}`,
        summary: `Summary for ${id}`,
        workingDirectory: null,
        gitBranch: null,
        messageCount: 5,
        embeddingStatus: 'complete' as const,
        startedAt: null,
        endedAt: null,
        importedAt: '2026-01-01T00:00:00Z',
        tags: [],
      })),
    };
    const src = new SessionsSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    const out = await src.search('q', { project_id: projectId }, 5);
    expect(out).toHaveLength(2);
    expect(out[0].source_type).toBe('sessions');
    expect(out[0].text).toBe('Summary for S1');
    expect(out[0].metadata.message_count).toBe(5);
  });

  it('forwards agent_token_id filter when provided', async () => {
    const store = mockStore([]);
    const storage = { getSession: vi.fn() };
    const src = new SessionsSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    await src.search(
      'q',
      { project_id: projectId, agent_token_id: 'agent-A' },
      5,
    );
    const filter = (store.search.mock.calls[0][2] ?? {}) as {
      must: Array<{ key: string; match: { value: string } }>;
    };
    expect(filter.must.some(c => c.key === 'agent_token_id' && c.match.value === 'agent-A')).toBe(true);
  });
});

describe('MessagesSource', () => {
  const projectId = '00000000-0000-0000-0000-000000000000';

  it('refuses to search without agent_token_id (privacy)', async () => {
    const store = mockStore([{ id: 'M', score: 0.9 }]);
    const storage = { getMessageById: vi.fn() };
    const src = new MessagesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    const out = await src.search('q', { project_id: projectId }, 5);
    expect(out).toEqual([]);
    expect(store.search).not.toHaveBeenCalled();
    expect(storage.getMessageById).not.toHaveBeenCalled();
  });

  it('hydrates messages by ID with agent_token_id filter', async () => {
    const store = mockStore([
      {
        id: 'point1',
        score: 0.92,
        payload: { message_id: 'msg-1', session_id: 'sess-1' },
      },
    ]);
    const storage = {
      getMessageById: vi.fn(async () => ({
        id: 'msg-1',
        sessionId: 'sess-1',
        role: 'user' as const,
        content: 'Hello world',
        messageIndex: 0,
        hasToolUse: false,
        toolNames: [],
        timestamp: null,
      })),
      getSession: vi.fn(async () => ({
        id: 'sess-1',
        agentTokenId: 'agent-A',
        projectId,
        externalId: null,
        name: null,
        summary: '',
        workingDirectory: null,
        gitBranch: null,
        messageCount: 1,
        embeddingStatus: 'complete' as const,
        startedAt: null,
        endedAt: null,
        importedAt: '2026-01-01T00:00:00Z',
        tags: [],
      })),
    };
    const src = new MessagesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    const out = await src.search(
      'q',
      { project_id: projectId, agent_token_id: 'agent-A' },
      5,
    );
    expect(out).toHaveLength(1);
    expect(out[0].source_type).toBe('session_messages');
    expect(out[0].text).toBe('Hello world');
    expect(out[0].metadata.role).toBe('user');
    expect(out[0].metadata.session_id).toBe('sess-1');
  });

  it('drops messages whose session belongs to a different project (cross-project leak guard)', async () => {
    const store = mockStore([
      {
        id: 'point-leak',
        score: 0.95,
        payload: { message_id: 'msg-leak', session_id: 'sess-foreign' },
      },
    ]);
    const storage = {
      getMessageById: vi.fn(),
      getSession: vi.fn(async () => ({
        id: 'sess-foreign',
        agentTokenId: 'agent-A',
        // Same agent, but the session was imported into a different project.
        projectId: '99999999-9999-4999-8999-999999999999',
        externalId: null,
        name: null,
        summary: '',
        workingDirectory: null,
        gitBranch: null,
        messageCount: 1,
        embeddingStatus: 'complete' as const,
        startedAt: null,
        endedAt: null,
        importedAt: '2026-01-01T00:00:00Z',
        tags: [],
      })),
    };
    const src = new MessagesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    const out = await src.search(
      'q',
      { project_id: projectId, agent_token_id: 'agent-A' },
      5,
    );
    expect(out).toEqual([]);
    expect(storage.getMessageById).not.toHaveBeenCalled();
  });
});

describe('EntriesSource — statuses filter', () => {
  const projectId = '00000000-0000-0000-0000-000000000000';

  it('hardcodes status=active when statuses filter is omitted', async () => {
    const store = mockStore([]);
    const storage = { getByIds: vi.fn(async () => []) };
    const src = new EntriesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    await src.search('q', { project_id: projectId }, 10);
    const filter = (store.search.mock.calls[0][2] ?? {}) as {
      must: Array<{ key: string; match: { value: string } }>;
    };
    expect(filter.must.find(c => c.key === 'status')?.match).toEqual({ value: 'active' });
  });

  it('uses any-match when statuses contains multiple values', async () => {
    const store = mockStore([]);
    const storage = { getByIds: vi.fn(async () => []) };
    const src = new EntriesSource(
      mockEmbed() as never,
      store as never,
      storage as never,
    );
    await src.search(
      'q',
      { project_id: projectId, statuses: ['active', 'completed'] },
      10,
    );
    const filter = (store.search.mock.calls[0][2] ?? {}) as {
      must: Array<{ key: string; match: { any: string[] } }>;
    };
    expect(filter.must.find(c => c.key === 'status')?.match).toEqual({
      any: ['active', 'completed'],
    });
  });
});
