import type { InsertEventParams, EventType } from './types.js';
import { EVENT_TYPES } from './types.js';
import { sampleMessagesForPrompt, detectLang } from '../extraction/prompt.js';

export interface BuildEventsPromptInput {
  summary: string;
  messages: Array<{ role: string; content: string }>;
}

export function buildEventsPrompt(input: BuildEventsPromptInput): string {
  const sampled = sampleMessagesForPrompt(input.messages);
  const conversation = sampled.map(m => `[${m.role}]: ${m.content.slice(0, 300)}`).join('\n');
  const lang = detectLang(input.summary + ' ' + conversation);

  return `You analyze a development session and extract concrete events that happened
during it. Events are WHAT-facts (something completed, deployed, broke) — NOT
WHY-knowledge (architecture decisions, conventions).

Event types you may extract:
- "merge"     — a branch/PR was merged into main (e.g. "смержил feat/X в main", "merged #42")
- "release"   — a version was released (e.g. "релиз v4.5", "tagged v1.2.0")
- "deploy"    — code was deployed to an environment (e.g. "задеплоил на staging")
- "incident"  — production issue / outage / bug discovered
- "milestone" — a major work milestone reached (e.g. "Phase 3 готова", "MVP закрыт")

For each event provide:
- "event_type": one of the 5 above
- "occurred_at": ISO timestamp when it happened (use session date if not explicit)
- "title": short identifier in ${lang}, 5-15 words
- "description": optional 1-2 sentences in ${lang}
- "refs": object — { pr_number, commit_sha, version_tag, deployment_url, incident_id } — include only what is mentioned
- "actor": who did it (only if explicitly named)
- "confidence": 0.0-1.0

ONLY extract events EXPLICITLY stated as having happened (past tense in completion context).
Do NOT extract:
- Plans ("надо смержить") — these are future
- Failures/blockers — those are incidents only if they hit prod
- Routine progress ("сделал task 5") — too noisy

If no events — return empty array. Empty is correct.

Output VALID JSON, no markdown:
{"events":[...]}

Session summary:
${input.summary}

Session transcript:
${conversation}`;
}

export function parseEventsResponse(
  raw: string,
  opts: { minConfidence?: number } = {},
): InsertEventParams[] {
  const minConf = opts.minConfidence ?? 0.7;
  let obj: unknown;
  try {
    obj = JSON.parse(raw);
  } catch {
    return [];
  }
  if (!obj || typeof obj !== 'object') return [];
  const eventsField = (obj as { events?: unknown }).events;
  if (!Array.isArray(eventsField)) return [];

  const result: InsertEventParams[] = [];
  for (const ev of eventsField) {
    if (!ev || typeof ev !== 'object') continue;
    const e = ev as Record<string, unknown>;
    if (!EVENT_TYPES.includes(e.event_type as EventType)) continue;
    if (typeof e.title !== 'string' || !e.title.trim()) continue;
    if (typeof e.occurred_at !== 'string') continue;
    if (typeof e.confidence !== 'number' || e.confidence < minConf) continue;

    result.push({
      projectId: '',
      eventType: e.event_type as EventType,
      occurredAt: e.occurred_at,
      title: (e.title as string).trim(),
      description: typeof e.description === 'string' ? e.description : undefined,
      refs: typeof e.refs === 'object' && e.refs !== null ? (e.refs as Record<string, unknown>) : {},
      actor: typeof e.actor === 'string' ? e.actor : undefined,
      autoGenerated: true,
    });
  }
  return result;
}
