import pg from 'pg';
import type {
  ProjectEvent,
  InsertEventParams,
  ListEventOptions,
} from './types.js';

export class EventsStorage {
  constructor(private pool: pg.Pool) {}

  async insert(params: InsertEventParams): Promise<ProjectEvent> {
    const occurred = params.occurredAt instanceof Date ? params.occurredAt.toISOString() : params.occurredAt;
    const { rows } = await this.pool.query(
      `INSERT INTO project_events
         (project_id, event_type, occurred_at, actor, title, description, refs, auto_generated, evidence_sources)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9::jsonb)
       RETURNING *`,
      [
        params.projectId,
        params.eventType,
        occurred,
        params.actor ?? null,
        params.title,
        params.description ?? null,
        JSON.stringify(params.refs ?? {}),
        params.autoGenerated ?? false,
        JSON.stringify(params.evidenceSources ?? []),
      ],
    );
    return this.rowToEvent(rows[0]);
  }

  async list(projectId: string, opts: ListEventOptions = {}): Promise<ProjectEvent[]> {
    const conds: string[] = ['project_id = $1'];
    const params: unknown[] = [projectId];
    if (opts.eventType) {
      params.push(opts.eventType);
      conds.push(`event_type = $${params.length}`);
    }
    if (opts.since) {
      const iso = opts.since instanceof Date ? opts.since.toISOString() : opts.since;
      params.push(iso);
      conds.push(`occurred_at >= $${params.length}`);
    }
    const limit = Math.max(1, Math.min(opts.limit ?? 50, 200));
    params.push(limit);
    const { rows } = await this.pool.query(
      `SELECT * FROM project_events
       WHERE ${conds.join(' AND ')}
       ORDER BY occurred_at DESC
       LIMIT $${params.length}`,
      params,
    );
    return rows.map(r => this.rowToEvent(r));
  }

  async delete(id: string): Promise<boolean> {
    const { rowCount } = await this.pool.query(
      `DELETE FROM project_events WHERE id = $1`,
      [id],
    );
    return (rowCount ?? 0) > 0;
  }

  private rowToEvent(row: Record<string, unknown>): ProjectEvent {
    const occurredAt = row.occurred_at as Date | string;
    const createdAt = row.created_at as Date | string;
    return {
      id: row.id as string,
      projectId: row.project_id as string,
      eventType: row.event_type as ProjectEvent['eventType'],
      occurredAt: typeof occurredAt === 'string' ? occurredAt : occurredAt.toISOString(),
      actor: (row.actor as string | null) ?? null,
      title: row.title as string,
      description: (row.description as string | null) ?? null,
      refs: (row.refs as ProjectEvent['refs']) ?? {},
      autoGenerated: row.auto_generated as boolean,
      evidenceSources: (row.evidence_sources as ProjectEvent['evidenceSources']) ?? [],
      createdAt: typeof createdAt === 'string' ? createdAt : createdAt.toISOString(),
    };
  }
}
