import type { EvidenceSource } from '../extraction/types.js';

export type EventType = 'merge' | 'release' | 'deploy' | 'incident' | 'milestone';

export const EVENT_TYPES: EventType[] = ['merge', 'release', 'deploy', 'incident', 'milestone'];

export interface EventRefs {
  pr_number?: number;
  commit_sha?: string;
  version_tag?: string;
  deployment_url?: string;
  incident_id?: string;
  [key: string]: unknown;
}

export interface ProjectEvent {
  id: string;
  projectId: string;
  eventType: EventType;
  occurredAt: string;        // ISO
  actor: string | null;
  title: string;
  description: string | null;
  refs: EventRefs;
  autoGenerated: boolean;
  evidenceSources: EvidenceSource[];
  createdAt: string;
}

export interface InsertEventParams {
  projectId: string;
  eventType: EventType;
  occurredAt: Date | string;
  actor?: string;
  title: string;
  description?: string;
  refs?: EventRefs;
  autoGenerated?: boolean;
  evidenceSources?: EvidenceSource[];
}

export interface ListEventOptions {
  eventType?: EventType;
  limit?: number;
  since?: Date | string;
}

export const EVENT_TYPE_ICONS: Record<EventType, string> = {
  merge:     '🔀',
  release:   '🚀',
  deploy:    '📦',
  incident:  '🚨',
  milestone: '🏁',
};
