// Категории памяти
export type Category =
  | 'architecture'  // Архитектурные решения (DEPRECATED v5 — read-only, collapsed into 'knowledge' by mig-022)
  | 'tasks'         // Текущие задачи (DEPRECATED v4.5)
  | 'decisions'     // Принятые решения (DEPRECATED v5)
  | 'issues'        // Известные проблемы (DEPRECATED v4.5)
  | 'progress'      // Прогресс разработки (DEPRECATED v4.5)
  | 'conventions'   // Конвенции проекта (DEPRECATED v5)
  | 'profile'       // Эталонный профиль проекта (one per project, v5)
  | 'knowledge';    // Объединённая категория для architecture/decisions/conventions (v5)

// Приоритеты
export type Priority = 'low' | 'medium' | 'high' | 'critical';

// Статусы записей
export type Status = 'active' | 'completed' | 'archived';

// Режимы синхронизации
export type SyncMode = 'auto' | 'manual' | 'both';

/** Default project UUID — used when no project_id is specified */
export const DEFAULT_PROJECT_ID = '00000000-0000-0000-0000-000000000000';

// Домены по умолчанию
export const DEFAULT_DOMAINS: string[] = [
  'backend',
  'frontend',
  'infrastructure',
  'devops',
  'database',
  'testing',
];

// Project roles — soft bias for auto-recall ordering
export type ProjectRole = 'developer' | 'qa' | 'lead' | 'devops';
export const PROJECT_ROLES: ProjectRole[] = ['developer', 'qa', 'lead', 'devops'];

/**
 * Role-aware recall biasing — v5 model.
 * Categories collapsed into 'knowledge'; old kind names now live in tags.
 * Both 'categories' (kept for back-compat with persisted role configs) and
 * 'tags' are checked: a role gets the boost if EITHER matches.
 */
// v5: tag list includes both singular (LLM-extractor output) and plural
// (legacy migration 022 output). Boost applies if entry has ANY listed tag.
export const ROLE_PRIORITIES: Record<ProjectRole, { categories: Category[]; tags: string[]; domains: string[]; boost: number }> = {
  developer: {
    categories: ['knowledge', 'profile'],
    tags: ['architecture', 'decision', 'decisions', 'convention', 'conventions'],
    domains: ['backend', 'frontend', 'database'],
    boost: 1.5,
  },
  qa: {
    categories: ['knowledge'],
    tags: ['convention', 'conventions', 'incident', 'testing'],
    domains: ['testing'],
    boost: 1.5,
  },
  lead: {
    categories: ['knowledge', 'profile'],
    tags: ['decision', 'decisions', 'milestone', 'release'],
    domains: [],
    boost: 1.3,
  },
  devops: {
    categories: ['knowledge'],
    tags: ['deploy', 'incident', 'infrastructure'],
    domains: ['infrastructure', 'devops'],
    boost: 1.5,
  },
};

export const ROLE_INFO: Record<ProjectRole, { name: string; nameEn: string; icon: string }> = {
  developer: { name: 'Разработчик', nameEn: 'Developer', icon: '💻' },
  qa:        { name: 'Тестировщик', nameEn: 'QA',        icon: '🧪' },
  lead:      { name: 'Руководитель', nameEn: 'Lead',      icon: '👔' },
  devops:    { name: 'DevOps',      nameEn: 'DevOps',    icon: '⚙️' },
};

// Проект
export interface Project {
  id: string;
  name: string;
  description: string;
  domains: string[];
  createdAt: string;
  updatedAt: string;
}

// Домен проекта (кастомный или дефолтный)
export interface ProjectDomain {
  id: string;
  projectId: string;
  slug: string;
  name: string;
  description: string;
  icon: string;
  sortOrder: number;
  isDefault: boolean;
  createdAt: string;
}

// Запись в памяти
export interface MemoryEntry {
  id: string;
  projectId: string;       // ID проекта
  category: Category;
  domain: string | null;   // Домен: backend, frontend, infrastructure, etc.
  title: string;
  content: string;
  author: string;
  tags: string[];
  priority: Priority;
  status: Status;
  pinned: boolean;
  createdAt: string;
  updatedAt: string;
  relatedIds: string[];
  currentVersion?: number; // Текущая версия записи (optimistic locking)
  readCount?: number;      // Количество чтений (для decay scoring)
  lastReadAt?: string;     // Последнее чтение (ISO string)
  autoGenerated?: boolean;
  extractionConfidence?: number | null;
  explicitMarkerStrength?: number | null;
  confirmationCount?: number;
  lastConfirmedAt?: string | null;
  evidenceSources?: import('../extraction/types.js').EvidenceSource[];
  externalRefs?: Record<string, unknown>;
  importanceScore?: number;
}

// Compact view — metadata only, no content
export interface CompactMemoryEntry {
  id: string;
  projectId: string;
  title: string;
  category: Category;
  domain: string | null;
  status: Status;
  priority: Priority;
  tags: string[];
  pinned: boolean;
  updatedAt: string;
  importanceScore?: number;
  confirmationCount?: number;
  autoGenerated?: boolean;
}

// Хранилище памяти (legacy, для миграции)
export interface MemoryStore {
  version: string;
  lastUpdated: string;
  entries: LegacyMemoryEntry[];
  metadata: {
    projectName: string;
    team: string[];
    createdAt: string;
  };
}

// Legacy entry format (v1, без projectId и domain)
export interface LegacyMemoryEntry {
  id: string;
  category: Category;
  title: string;
  content: string;
  author: string;
  tags: string[];
  priority: Priority;
  status: Status;
  pinned: boolean;
  createdAt: string;
  updatedAt: string;
  relatedIds: string[];
}

// Конфигурация сервера
export interface ServerConfig {
  dataPath: string;
  webPort: number;
  wsPort: number;
  syncMode: SyncMode;
  backupEnabled: boolean;
  backupInterval: number;
  autoArchiveEnabled: boolean;
  autoArchiveDays: number;
}

// Параметры для чтения памяти
export interface ReadParams {
  projectId?: string;
  category?: Category | 'all';
  domain?: string;
  search?: string;
  limit?: number;
  offset?: number;
  status?: Status;
  tags?: string[];
  ids?: string[];
  mode?: 'compact' | 'full';
  pinned?: boolean;
}

// Параметры для записи в память
export interface WriteParams {
  projectId?: string;
  category: Category;
  domain?: string;
  title: string;
  content: string;
  author?: string;
  tags?: string[];
  priority?: Priority;
  pinned?: boolean;
  relatedIds?: string[];
}

// Параметры для обновления записи
export interface UpdateParams {
  id: string;
  expectedVersion?: number; // Optimistic locking: обновление только если версия совпадает
  title?: string;
  content?: string;
  domain?: string | null;
  status?: Status;
  tags?: string[];
  priority?: Priority;
  pinned?: boolean;
  relatedIds?: string[];
}

// Ошибка конфликта версий (optimistic locking)
export interface ConflictError {
  conflict: true;
  currentVersion: number;
  currentEntry: MemoryEntry;
  message: string;
}

// Параметры для удаления/архивации
export interface DeleteParams {
  id: string;
  archive?: boolean;
  /**
   * Optimistic-lock guard. When provided, archive=true delegates to
   * archive(id, expectedVersion) which returns a ConflictError instead of
   * silently succeeding if the entry was modified between the caller's
   * read and the archive call. Ignored when archive=false (hard delete is
   * unconditional).
   */
  expectedVersion?: number;
}

// Параметры синхронизации
export interface SyncParams {
  projectId?: string;
  since?: string; // ISO date string
}

// Результат синхронизации
export interface SyncResult {
  entries: MemoryEntry[];
  lastUpdated: string;
  totalChanges: number;
}

// События WebSocket
export type WSEventType =
  | 'memory:created'
  | 'memory:updated'
  | 'memory:deleted'
  | 'memory:sync'
  | 'agent:connected'
  | 'agent:disconnected';

export interface WSEvent {
  type: WSEventType;
  payload: unknown;
  timestamp: string;
}

// Статистика для UI
export interface MemoryStats {
  totalEntries: number;
  pinnedCount: number;
  byCategory: Record<Category, number>;
  byDomain: Record<string, number>;
  byStatus: Record<Status, number>;
  byPriority: Record<Priority, number>;
  recentActivity: {
    last24h: number;
    last7d: number;
  };
  connectedAgents: number;
}

// Описания категорий для UI
export const CATEGORY_INFO: Record<Category, { name: string; description: string; icon: string }> = {
  architecture: {
    name: 'Архитектура',
    description: 'Архитектурные решения, выбор стека, структура проекта',
    icon: '🏗️'
  },
  tasks: {
    name: 'Задачи',
    description: 'Текущие задачи, в работе, запланированные',
    icon: '📋'
  },
  decisions: {
    name: 'Решения',
    description: 'Принятые решения и их обоснование',
    icon: '✅'
  },
  issues: {
    name: 'Проблемы',
    description: 'Известные проблемы, баги, технический долг',
    icon: '🐛'
  },
  progress: {
    name: 'Прогресс',
    description: 'Прогресс разработки, завершённые этапы',
    icon: '📈'
  },
  conventions: {
    name: 'Конвенции',
    description: 'Стиль кода, архитектурные паттерны, правила проекта',
    icon: '📏'
  },
  profile: {
    name: 'Профиль',
    description: 'Эталонная запись «как погрузиться в проект» — всегда показывается агенту первой',
    icon: '🗺️'
  },
  knowledge: {
    name: 'Знания',
    description: 'WHY-факты: архитектурные решения, паттерны, конвенции — объединённая категория (v5)',
    icon: '📚'
  }
};

// Цвета приоритетов для UI
export const PRIORITY_COLORS: Record<Priority, string> = {
  low: '#6b7280',
  medium: '#3b82f6',
  high: '#f59e0b',
  critical: '#ef4444'
};

// Цвета статусов для UI
export const STATUS_COLORS: Record<Status, string> = {
  active: '#22c55e',
  completed: '#6b7280',
  archived: '#9ca3af'
};

// Информация о доменах
export const DOMAIN_INFO: Record<string, { name: string; icon: string }> = {
  backend: { name: 'Бэкенд', icon: '🖥️' },
  frontend: { name: 'Фронтенд', icon: '🎨' },
  infrastructure: { name: 'Инфраструктура', icon: '🏗️' },
  devops: { name: 'DevOps', icon: '⚙️' },
  database: { name: 'База данных', icon: '🗄️' },
  testing: { name: 'Тестирование', icon: '🧪' },
};

// Default domain metadata for project_domains table (Lucide icons + descriptions)
export const DEFAULT_DOMAIN_META: Record<string, { name: string; icon: string; description: string }> = {
  backend:        { name: 'Backend',        icon: 'server',     description: 'Серверная логика, API, бизнес-логика' },
  frontend:       { name: 'Frontend',       icon: 'monitor',    description: 'Клиентская часть, UI/UX' },
  infrastructure: { name: 'Infrastructure', icon: 'network',    description: 'Инфраструктура, сети, серверы' },
  devops:         { name: 'DevOps',         icon: 'container',  description: 'CI/CD, деплой, мониторинг' },
  database:       { name: 'Database',       icon: 'database',   description: 'Базы данных, миграции, схемы' },
  testing:        { name: 'Testing',        icon: 'test-tubes', description: 'Тестирование, QA' },
};
