// src/retrieval/sources/entries-source.ts
//
// KnowledgeSource that surfaces team-memory entries (the durable knowledge
// captured by manual share + auto-extraction). Embeds the query, runs a
// project-scoped Qdrant search against the `entries` collection, and
// hydrates results from PostgreSQL.

import type {
  KnowledgeSource,
  KnowledgeChunk,
  RetrievalFilters,
} from '../types.js';
import type { EmbeddingProvider } from '../../embedding/provider.js';
import type { VectorStore, VectorFilter } from '../../vector/vector-store.js';
import type { PgStorage } from '../../storage/pg-storage.js';

export class EntriesSource implements KnowledgeSource {
  readonly type = 'entries' as const;

  constructor(
    private embedding: EmbeddingProvider,
    private vector: VectorStore,
    private storage: PgStorage,
  ) {}

  async search(
    query: string,
    filters: RetrievalFilters,
    limit: number,
  ): Promise<KnowledgeChunk[]> {
    if (!this.embedding.isReady()) return [];
    const vec = await this.embedding.embed(query, 'query');

    const f: VectorFilter = {
      must: [{ key: 'project_id', match: { value: filters.project_id } }],
    };
    // Default to active entries only — unless caller explicitly broadens.
    f.must!.push({ key: 'status', match: { value: 'active' } });
    if (filters.categories?.length) {
      f.should = filters.categories.map(c => ({
        key: 'category',
        match: { value: c },
      }));
    }

    const results = await this.vector.search('entries', vec, f, limit);
    if (results.length === 0) return [];

    // Hydrate via PG getByIds — preserves authoritative state (status, tags
    // updated since the vector was written, etc).
    const ids = results.map(r => String(r.id));
    const entries = await this.storage.getByIds(filters.project_id, ids);
    const byId = new Map(entries.map(e => [e.id, e]));

    const out: KnowledgeChunk[] = [];
    for (const r of results) {
      const e = byId.get(String(r.id));
      if (!e) continue;
      out.push({
        source_type: 'entries',
        source_id: e.id,
        text: `${e.title}\n\n${e.content}`,
        score: r.score,
        metadata: {
          category: e.category,
          importance_score: e.importanceScore,
          confirmation_count: e.confirmationCount,
          pinned: e.pinned,
          tags: e.tags,
          auto_generated: e.autoGenerated,
        },
      });
    }
    return out;
  }
}
